version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: rafa
      ME_CONFIG_BASICAUTH_PASSWORD:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2021!
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2021!
    ports:
      - "27017:27017"
    volumes:
      # - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
      - C:\Dev\Projetos\react\my-money-manager\backend\Docker\Volumes\MongoDB:\data\db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge